[project]
name = "ltrim"
version = "0.1.2"
description = "ASPLOS'25 AE branch for Î»-trim"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "psutil>=6.1.1",
    "pycg-fork",
    "ruff>=0.9.2",
    "setuptools>=75.8.0",
]

[project.scripts]
debloat = "ltrim:debloat"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # flake8-bugbear
    "B",
    # isort
    "I",
]
